trigger: none

pool: Default

schedules:
- cron: string # Required as first property. Cron syntax defining a schedule in UTC time.
  displayName: string # Optional friendly name given to a specific schedule.
  branches: # Branch names to include or exclude for triggering a run.
    include: [ string ] # List of items to include.
    exclude: [ string ] # List of items to exclude.
  batch: boolean # Whether to run the pipeline if the previously scheduled run is in-progress; the default is false.
  always: boolean # Whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run; the default is false

stages:
- stage: StopVM
  displayName: Stop VM at 9 PM
  jobs:
  - job: VMSTOP
    displayName: VM Stop Job
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Finops Service Connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm deallocate --resource-group production01 --name VM1'