trigger: none

pool: Default

schedules:
- cron: '30 2 * * *'
  displayName: Start VM At 8 AM
  branches:
    include:
    - main
  always: true 


variables:
- group: VM-Details

stages:
- stage: StartVM
  displayName: Start VM at 8 AM
  jobs:
  - job: VMStart
    displayName: VM Start Job
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Finops Service Connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $vmNames = $(VM-Name) -split ","
                    foreach ($vmName in $vmNames) {
                      az vm start --resource-group $(RG-Name) --name $vmName.Trim('"')
                    }