trigger: none

pool: Default

schedules:
- cron: '30 14 * * *'
  displayName: Stop VM At 8 PM
  branches:
    include:
    - main
  always: true 

variables:
- group: VM-Details

stages:
- stage: StopVM
  displayName: Stop VM at 8 PM
  jobs:
  - job: VMSTOP
    displayName: VM Stop Job
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Finops Service Connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $vmNames = $(VM-Name) -split ","
                    foreach ($vmName in $vmNames) {
                      az vm deallocate --resource-group $(RG-Name) --name $vmName.Trim('"')
                    }