trigger: none

pool: Default

schedules:
- cron: '05 11 * * *'
  displayName: Start VM At 4 PM
  branches:
    include:
    - main
  always: true 


variables:
  RG-Name: production01
  VM-Name: VM1

stages:
- stage: StartVM
  displayName: Start VM at 4 PM
  jobs:
  - job: VMStart
    displayName: VM Start Job
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Finops Service Connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm start --resource-group $(RG-Name) --name $(VM-Name)'